
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author phamh
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        //jPanelTongQuan = new TongQuan();
        jPanelDanhMuc = new DanhMuc();
        jPanelThietLapGia = new ThietLapGia();
        
        
        initComponents();
        
        
        //xóa panel hiện tại
        jPanelContent.removeAll();
        jPanelContent.repaint();
        jPanelContent.revalidate();
        
        //ve panel tong quan
        jPanelContent.add(jPanelDanhMuc);
        jPanelContent.repaint();
        jPanelContent.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContent = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuTongQuan = new javax.swing.JMenu();
        jMenuHangHoa = new javax.swing.JMenu();
        jMenuItemDanhMuc = new javax.swing.JMenuItem();
        jMenuItemThietLapGia = new javax.swing.JMenuItem();
        jMenuItemKiemKho = new javax.swing.JMenuItem();
        jMenuGiaoDich = new javax.swing.JMenu();
        jMenuDoiTac = new javax.swing.JMenu();
        jMenuSoQuy = new javax.swing.JMenu();
        jMenuBaoCao = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(100, 50));
        setPreferredSize(new java.awt.Dimension(1200, 700));

        jPanelContent.setLayout(new java.awt.CardLayout());

        jMenuBar.setPreferredSize(new java.awt.Dimension(326, 25));

        jMenuTongQuan.setBorder(null);
        jMenuTongQuan.setText("Tổng quan");
        jMenuTongQuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTongQuanActionPerformed(evt);
            }
        });
        jMenuBar.add(jMenuTongQuan);

        jMenuHangHoa.setText("Hàng hóa");
        jMenuHangHoa.setMinimumSize(new java.awt.Dimension(100, 19));

        jMenuItemDanhMuc.setText("Danh mục");
        jMenuItemDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDanhMucActionPerformed(evt);
            }
        });
        jMenuHangHoa.add(jMenuItemDanhMuc);

        jMenuItemThietLapGia.setText("Thiết lập giá");
        jMenuItemThietLapGia.setActionCommand("");
        jMenuItemThietLapGia.setPreferredSize(new java.awt.Dimension(100, 22));
        jMenuItemThietLapGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemThietLapGiaActionPerformed(evt);
            }
        });
        jMenuHangHoa.add(jMenuItemThietLapGia);

        jMenuItemKiemKho.setText("Kiểm kho");
        jMenuItemKiemKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKiemKhoActionPerformed(evt);
            }
        });
        jMenuHangHoa.add(jMenuItemKiemKho);

        jMenuBar.add(jMenuHangHoa);

        jMenuGiaoDich.setText("Giao dịch");
        jMenuBar.add(jMenuGiaoDich);

        jMenuDoiTac.setText("Đối tác");
        jMenuBar.add(jMenuDoiTac);

        jMenuSoQuy.setText("Sổ quỹ");
        jMenuBar.add(jMenuSoQuy);

        jMenuBaoCao.setText("Báo cáo");
        jMenuBar.add(jMenuBaoCao);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemKiemKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKiemKhoActionPerformed
        // TODO add your handling code here:

        //xóa panel hiện tại
        jPanelContent.removeAll();
        jPanelContent.repaint();
        jPanelContent.revalidate();

        //ve panel tong quan
        jPanelContent.add(jPanelTongQuan);
        jPanelContent.repaint();
        jPanelContent.revalidate();
    }//GEN-LAST:event_jMenuItemKiemKhoActionPerformed

    private void jMenuItemThietLapGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemThietLapGiaActionPerformed
        // TODO add your handling code here:
        //xóa panel hiện tại
        jPanelContent.removeAll();
        jPanelContent.repaint();
        jPanelContent.revalidate();

        //ve panel thiet lap gia
        jPanelContent.add(jPanelThietLapGia);
        jPanelContent.repaint();
        jPanelContent.revalidate();
    }//GEN-LAST:event_jMenuItemThietLapGiaActionPerformed

    private void jMenuItemDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDanhMucActionPerformed
        // TODO add your handling code here:
        //xóa panel hiện tại
        jPanelContent.removeAll();
        jPanelContent.repaint();
        jPanelContent.revalidate();

        //ve panel danh muc
        jPanelContent.add(jPanelDanhMuc);
        jPanelContent.repaint();
        jPanelContent.revalidate();
    }//GEN-LAST:event_jMenuItemDanhMucActionPerformed

    private void jMenuTongQuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTongQuanActionPerformed
        
        // TODO add your handling code here:
        System.out.println("You clicked the JMenu");
        JOptionPane.showMessageDialog(null, "My Goodness, this is so concise");
        
        //xóa panel hiện tại
        jPanelContent.removeAll();
        jPanelContent.repaint();
        jPanelContent.revalidate();

        //ve panel tong quan
        jPanelContent.add(jPanelTongQuan);
        jPanelContent.repaint();
        jPanelContent.revalidate();
    }//GEN-LAST:event_jMenuTongQuanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    
    private ThietLapGia jPanelThietLapGia;
    private DanhMuc jPanelDanhMuc;
    private TongQuan jPanelTongQuan;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuBaoCao;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuDoiTac;
    private javax.swing.JMenu jMenuGiaoDich;
    private javax.swing.JMenu jMenuHangHoa;
    private javax.swing.JMenuItem jMenuItemDanhMuc;
    private javax.swing.JMenuItem jMenuItemKiemKho;
    private javax.swing.JMenuItem jMenuItemThietLapGia;
    private javax.swing.JMenu jMenuSoQuy;
    private javax.swing.JMenu jMenuTongQuan;
    private javax.swing.JPanel jPanelContent;
    // End of variables declaration//GEN-END:variables
}
